- name: Upgrade Ubuntu Hosts
  hosts: ubuntu
  become: true
  vars:
    weekday_overwrite: false
  tasks:        
    - name: debug
      debug:
        var: weekday_run
        
    - name: Check Weekday or Overwrite
      meta: end_play
      when:
        - not weekday_overwrite
        - ansible_date_time.weekday_number != weekday_run
        
    - name: Autoremove Using Apt
      apt:
        update_cache: no
        upgrade: 'no'
        autoremove: yes

    - name: Upgrade Using Apt
      apt:
        update_cache: yes
        upgrade: dist

    - name: Check APT Based Servers for Restart
      shell: if [ -f /var/run/reboot-required ]; then echo '1'; else echo '0'; fi
      register: restart
      changed_when: restart.stdout == "1"

    - name: Restart Servers
      reboot:
        msg: Rebooting to complete system upgrade.
        post_reboot_delay: 10
        pre_reboot_delay: 10
        reboot_timeout: 3600
      when:
        - restart_apt.stdout is defined
        - restart_apt.stdout == "1"

